### ISSUE TITLE
Plot datestamp / timeline

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/gage-conditions-gif#11]
MVP: print the date

Next option: linear timeline with non-interactive "slider", e.g.:
![image](https://user-images.githubusercontent.com/12039957/47748858-25918680-dc62-11e8-9e44-f2a26f6e4d48.png)

Explore: github-style grid of dates, e.g.:
![image](https://user-images.githubusercontent.com/12039957/47748879-34783900-dc62-11e8-88a4-fa88651d4488.png)

**Comment by aappling-usgs** [comment]
MVP achieved in #40

**Comment by aappling-usgs** [comment]
No need to show times in the timestamp if we stick with text

**Comment by lindsaycarr** [comment]
For posterity: here's the grid: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13220910/48514188-5c9b9680-e823-11e8-9ca0-1605e33e52c3.gif)

**Comment by aappling-usgs** [comment]
The grid is also cool. I bet we'll find an occasion to use it in some future viz.
