### ISSUE TITLE
More contrasting between map + background

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#115]
Jordan & Mike would like to see options with the map popping a bit more. Looks a bit washed out at the moment.

**Comment by lindsaycarr** [comment]
### Option 1

Changes:

- basemap > col: `#cecece`
- basemap > border: `white`
- gage_style > with_percentile > normal > bg: `#bfbfbf` 

![image](https://user-images.githubusercontent.com/13220910/52595135-bc99dd00-2e12-11e9-963f-17895684a3b1.png)

**Comment by lindsaycarr** [comment]
### Option 2

- basemap > col: `#e5e5e5`
- basemap > border: `white`
- gage_style > with_percentile > normal > bg: no change from current state (so `#bfbfbf` )

![image](https://user-images.githubusercontent.com/13220910/52595869-8b221100-2e14-11e9-99bb-e2d7960829fa.png)

**Comment by lindsaycarr** [comment]
### Option 3

- basemap > col: `#e5e5e5`
- basemap > border: `white`
- gage_style > with_percentile > normal > bg: `#d7d7d7`

![image](https://user-images.githubusercontent.com/13220910/52596648-75ade680-2e16-11e9-8b55-5a53b2c8b361.png)

**Comment by lindsaycarr** [comment]
I, personally, like option 3 the best. So here is option 3 with two different line thicknesses:

#### lwd = 1.0

![image](https://user-images.githubusercontent.com/13220910/52596858-f836a600-2e16-11e9-9472-242ea3ed4dd9.png)

#### lwd = 1.5

![image](https://user-images.githubusercontent.com/13220910/52596913-1ef4dc80-2e17-11e9-9297-042faa470315.png)

#### lwd = 2.0

![image](https://user-images.githubusercontent.com/13220910/52596966-38962400-2e17-11e9-86f4-3cd3bc8e230d.png)

**Comment by jread-usgs** [comment]
I think I prefer the thicker line (but note that _not_ drawing a border around PR, AK, and HI would probably be :+1: if possible).

**Comment by lindsaycarr** [comment]
Just thought about the other challenge with this approach - our current event shapes are grey which has been working very well. What should we switch to now/ something white to bring attention to the area, maybe.

**Comment by jread-usgs** [comment]
Good point. Also, can/should the interior border lines be thicker yet?

**Comment by lindsaycarr** [comment]
Closed by #118
