### ISSUE TITLE
Frame-specific call-outs mid-animation

### ISSUE THREAD

**Issue by wdwatkins** [USGS-VIZLAB/gage-conditions-gif#5]
Ideally, would be able to reference frames by date rather than frame number

MVP: show just text 

Slow down frames and visually focus on certain gages over others (everything but the important region is greyed out). Would need to make it obvious that time has slowed. The "outro" part of viz storm gif has an example of this.

**Comment by jread-usgs** [comment]
Good thinking. And also, we'll want to be able to specify a start and an end date/frame for each callout. An example is the formation of a drought (could last a month or year) vs a flood (3~10 days).

**Comment by wdwatkins** [comment]
thinking about the mechanics of this, can we just have a callout for every frame, but leave it null/NA when we don't want one?  Then just remove null/NA functions at the final step before all the different  plots are rendered.

**Comment by wdwatkins** [comment]
(assuming there is a single callout plot function for each frame, same as gages/legend etc)

**Comment by jread-usgs** [comment]
I have the task to put together a proposal for #31 - I have a pattern in mind but need to put it down in the issue. I'm curious about your idea though, does it limit us to a single callout at one time? What about the situation when we have a flood in one part of CONUS and a drought in another? I was imagining the flexibility to handle similar would be necessary.

**Comment by wdwatkins** [comment]
Hmm, yeah, we could want to have callouts that partially overlap in time, so it might be best to only have a single callout per plot function so that their date ranges can be controlled independently.  I suppose you could simply have multiple NA/null plot functions though that get filtered out before rendering.
