### ISSUE TITLE
Flip the legend to be vertical?

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#56]
This would make it possible to place to the left of the map and use up that empty space.

**Comment by jread-usgs** [comment]
Probably depends on #11 for figuring out the layout of the frame, right?

**Comment by lindsaycarr** [comment]
Vertical, but now we have more to decide:


1. with or without arrows?

![image](https://user-images.githubusercontent.com/13220910/49669937-975eac00-fa28-11e8-8ef0-937fcfae998d.png)

2. above or below date wheel?

![image](https://user-images.githubusercontent.com/13220910/49669947-a180aa80-fa28-11e8-896f-2ff22ca564a0.png)

**Comment by lindsaycarr** [comment]
Chose no arrows, and wheel below legend.
