### ISSUE TITLE
Improve resolution

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#73]

**Comment by aappling-usgs** [comment]
* First step: can a Mac do this better?
* Are there ffmpeg settings we can play with?
* Do we need to improve png resolution even more to get a decent resolution in the movie? Note that png resolution is better than movie resolution right now.

**Comment by lindsaycarr** [comment]
Turns out webm was the cause of a lot of clarity issues. Mp4 format (#75) + rendering on a Mac makes this 👍. Could sacrifice some clarity in favor of dropping the size, but good for now. 

Gif w/ 365 frames was 18.6 MB.
Webm w/ 365 frames was 1 MB.
Mp4 w/ 365 frames is 9 MB.
