### ISSUE TITLE
Fix color ramp function

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#74]
We don't think this line is working as it should. https://github.com/USGS-VIZLAB/gage-conditions-gif/blob/master/2_process/src/process_dv_stat_colors.R#L18

It is using the entire vector of percentiles for the whole year to figure out what colors they should correspond to. What if this particular year saw more daily discharges that were above 50th percentile? Then our vector would be skewed and the color ramp function would match a value > 50th %ile to our "median" color, white. Investigating further to figure out if that is going on. 

A potential solution is to use `col_fun` with just the 0, 0.5, and 1 percentiles and then use `breaks` or `cut` to match our vector of percentiles to a color range.

**Comment by lindsaycarr** [comment]
Conclusion: concern debunked! It works fine and doesn't need fixing. `colorRamp` appears to automatically operate based on a scale from [0,1], so our percentiles are automatically interpreted appropriately. Verified using the code below.

```r
color_palette <- c("#ca0020", "#f4a582", "#efefef", "#efefef", "#92c5de", "#034064")
col_fun <- colorRamp(color_palette)

# data that is even on both sides of the "middle"
even_data <- c(0.1, 0.5, 0.9)
even_data_cols <- rgb(col_fun(even_data), maxColorValue = 255)
plot(1:length(even_data), rep(2, length(even_data)), pch = 20, cex=3, 
     col = even_data_cols, axes = FALSE, xlab = "", ylab = "")
```
![image](https://user-images.githubusercontent.com/13220910/48570785-c28f2900-e8ca-11e8-8a13-cdcc10adbefc.png)


```r
# data where there are more percentiles greater than the 50th
odd_data <- c(0.1, 0.5, 0.6, 0.75, 0.72, 0.9)
odd_data_cols <- rgb(col_fun(odd_data), maxColorValue = 255)
plot(1:length(odd_data), rep(2, length(odd_data)), pch = 20, cex=3, 
     col = odd_data_cols, axes = FALSE, xlab = "", ylab = "")
```
![image](https://user-images.githubusercontent.com/13220910/48570801-cfac1800-e8ca-11e8-9669-e915182701c6.png)


```r
# data where there are more percentiles less than the 50th
odd_data2 <- c(0.01, 0.2, 0.33, 0.43, 0.5)
odd_data_cols2 <- rgb(col_fun(odd_data2), maxColorValue = 255)
plot(1:length(odd_data2), rep(2, length(odd_data2)), pch = 20, cex=3, 
     col = odd_data_cols2, axes = FALSE, xlab = "", ylab = "")
```
![image](https://user-images.githubusercontent.com/13220910/48570820-ddfa3400-e8ca-11e8-81bb-a52678ae30e9.png)

```r
# data where there are no 50th percentiles 
no50_data <- c(0.01, 0.2, 0.33, 0.43, 0.9)
no50_data_cols <- rgb(col_fun(no50_data), maxColorValue = 255)
plot(1:length(no50_data), rep(2, length(no50_data)), pch = 20, cex=3, 
     col = no50_data_cols, axes = FALSE, xlab = "", ylab = "")
```

![image](https://user-images.githubusercontent.com/13220910/48570845-f0746d80-e8ca-11e8-92ce-695ff376934c.png)

**Comment by lindsaycarr** [comment]
So, if we wanted to change the range of the white color to say that "normal" captures a larger range of percentiles, we would need to rescale the percentiles that fit in our normal range to be equal to 0.5. Something like this should do the trick:

```
dv_stats_adjusted <- dplyr::mutate(dv_stats, per_adjusted = ifelse(per >= 0.4 && per <= 0.6, yes = 0.5, no = per)
```

**Comment by aappling-usgs** [comment]
Phew!
