### ISSUE TITLE
Show hydrologic events length & type

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#81]
Sandra ask `Is there a way to make it more clear how long a particular hydrologic event lasted? (e.g. a date range in the call out?) ... ` on 11/19. 

I think this would be harder for droughts, but we could try to do something on the date wheel.

**Comment by lindsaycarr** [comment]
This task should prototype some examples via rudimentary means (take one frame and use paint/photoshop/powerpoint) and share via Slack before implementing a code-based solution.

**Comment by lindsaycarr** [comment]
![frame_20180715_00_test_event_length_3](https://user-images.githubusercontent.com/13220910/49674553-02fc4580-fa38-11e8-8d49-15fb81bffe04.png)
![frame_20180715_00_test_event_length_2](https://user-images.githubusercontent.com/13220910/49674554-02fc4580-fa38-11e8-85c5-4b5589752a7e.png)
![frame_20180715_00_test_event_length_1](https://user-images.githubusercontent.com/13220910/49674555-02fc4580-fa38-11e8-9f04-a18b3b250499.png)

**Comment by aappling-usgs** [comment]
They all get the job done, but I like Option 3 the best. The colors on the wheel could be permanent (maybe light red before and dark red after the date has passed, like in Google Calendar event coloring?) - that would make it easier for users to notice the feature. Would also make it easier to slide the movie through time until the date lands on a callout you wanted to visit/revisit.

**Comment by aappling-usgs** [comment]
And we could make each event less thick than the width of the donut so that multiple simultaneous events could coexist on the wheel.

**Comment by lindsaycarr** [comment]
`wheel_color` and `wheel_color_passed` in viz_config for the callouts

**Comment by lindsaycarr** [comment]
Here's a quick implementation of this. Do we hate it or like it? Style changes (general colors + color changing if it's before/after the event) and dealing with overlapping events is planned, but only if we move forward.

![image](https://user-images.githubusercontent.com/13220910/51865038-fba43a80-230a-11e9-9c47-aa75ee00e4d0.png)

**Comment by aappling-usgs** [comment]
How do the colors change before/after? I'd prefer just one or two colors, maybe even sticking with reds and blues for droughts and floods. Does it work to place those event bars within the already-shaded rim of the color wheel?

PS - For the wet-dry legend, I think "drier" and "driest" (instead of with a y) would be a bit more conventional.

**Comment by lindsaycarr** [comment]
As you suggested in a couple comments above, they would be light/darker shade depending on whether the event has happened or not (like Google Cal events). 

Yes, I was thinking maybe just reds or blues - then they could be added to the legend. The challenge is when there are two blue or two red events overlapping. I think we would need a border. Yes, I could try adding them to the inside. I guess I thought they would be easier to see on the outside, but that was a hypothesis. I'll try it and see.

(thanks for pointing that out!)

**Comment by lindsaycarr** [comment]
New iteration (still not taking care of overlapping events, but I have an idea): 

![image](https://user-images.githubusercontent.com/13220910/51937360-0f65a480-23d0-11e9-805d-98777417734e.png)


![image](https://user-images.githubusercontent.com/13220910/51937347-04ab0f80-23d0-11e9-82ab-bfdd660425d5.png)

**Comment by aappling-usgs** [comment]
I like it!

**Comment by lindsaycarr** [comment]
Overlapping events. I put a note in the code that this only works for two overlapping and would need to be changed if there were more overlapping at any one time. Seems like too much an edge case to handle now.

![image](https://user-images.githubusercontent.com/13220910/51939134-5eadd400-23d4-11e9-88fb-1980469a23fd.png)
