### ISSUE TITLE
Investigate accuracy of data for some events

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#85]
From Sandy: 
```
The animation doesn't seem to capture the true impact of some of the hydrologic events. For example, the dots just outside the Hurricane Florence show as high (or even higher) relative flows as the dots inside the hurricane affected area. Was that indeed the case? At present, the hurricane seems to have been a non-issue, but I recall hearing about substantial flooding. Was the flooding throughout the mid-Atlantic equal in magnitude?
```

Not sure why they don't pop, but I agree that they don't stand out from the rest of the mid-Atlantic. I know that VA and MD were also experiencing a pretty wet Aug/Sep and rains from Hurricane Florence did make their way to those regions.

**Comment by wdwatkins** [comment]
Maybe the color scale saturates?  Florence set all-time records for some gages, how does the interpolation between percentiles handle that?

**Comment by lindsaycarr** [comment]
After merging #95, we are seeing Florence pop like we would expect.
